import { Student, FaultType, Incident, User, DashboardStats } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'supervisor1',
    fullName: 'María González',
    email: 'mgonzalez@escuela.edu',
    role: 'supervisor',
    active: true,
  },
  {
    id: '2',
    username: 'tutor1',
    fullName: 'Carlos Ramírez',
    email: 'cramirez@escuela.edu',
    role: 'tutor',
    active: true,
  },
  {
    id: '3',
    username: 'director',
    fullName: 'Ana Martínez',
    email: 'amartinez@escuela.edu',
    role: 'director',
    active: true,
  },
];

export const mockStudents: Student[] = [
  {
    id: '1',
    firstName: 'Juan',
    lastName: 'Pérez García',
    fullName: 'Juan Pérez García',
    grade: '5to',
    section: 'A',
    barcode: '2024050001',
    reincidenceLevel: 0,
    faultsLast60Days: 0,
    active: true,
  },
  {
    id: '2',
    firstName: 'María',
    lastName: 'López Sánchez',
    fullName: 'María López Sánchez',
    grade: '5to',
    section: 'A',
    barcode: '2024050002',
    reincidenceLevel: 1,
    faultsLast60Days: 2,
    active: true,
  },
  {
    id: '3',
    firstName: 'Carlos',
    lastName: 'Rodríguez Díaz',
    fullName: 'Carlos Rodríguez Díaz',
    grade: '5to',
    section: 'B',
    barcode: '2024050003',
    reincidenceLevel: 3,
    faultsLast60Days: 6,
    active: true,
  },
  {
    id: '4',
    firstName: 'Ana',
    lastName: 'Martínez Torres',
    fullName: 'Ana Martínez Torres',
    grade: '4to',
    section: 'A',
    barcode: '2024040001',
    reincidenceLevel: 0,
    faultsLast60Days: 0,
    active: true,
  },
  {
    id: '5',
    firstName: 'Luis',
    lastName: 'Fernández Ruiz',
    fullName: 'Luis Fernández Ruiz',
    grade: '6to',
    section: 'C',
    barcode: '2024060001',
    reincidenceLevel: 2,
    faultsLast60Days: 4,
    active: true,
  },
];

export const mockFaultTypes: FaultType[] = [
  {
    id: '1',
    code: 'COND-001',
    name: 'Falta de respeto a compañeros',
    description: 'Actitud irrespetuosa o agresiva hacia otros estudiantes',
    category: 'Conducta',
    severity: 'Grave',
    points: 3,
    active: true,
  },
  {
    id: '2',
    code: 'COND-002',
    name: 'Uso de lenguaje inapropiado',
    description: 'Uso de palabras ofensivas o vulgares',
    category: 'Conducta',
    severity: 'Leve',
    points: 1,
    active: true,
  },
  {
    id: '3',
    code: 'UNIF-001',
    name: 'Uniforme incompleto',
    description: 'Falta de prendas del uniforme escolar',
    category: 'Uniforme',
    severity: 'Leve',
    points: 1,
    active: true,
  },
  {
    id: '4',
    code: 'ACAD-001',
    name: 'No presenta tarea',
    description: 'Incumplimiento de entrega de tareas asignadas',
    category: 'Académica',
    severity: 'Leve',
    points: 1,
    active: true,
  },
  {
    id: '5',
    code: 'PUNT-001',
    name: 'Llegada tarde',
    description: 'Ingreso después de la hora establecida',
    category: 'Puntualidad',
    severity: 'Leve',
    points: 1,
    active: true,
  },
  {
    id: '6',
    code: 'COND-003',
    name: 'Pelea o agresión física',
    description: 'Contacto físico violento con otro estudiante',
    category: 'Conducta',
    severity: 'Grave',
    points: 5,
    active: true,
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'INC-2024-001',
    studentId: '3',
    student: mockStudents[2],
    faultTypeId: '1',
    faultType: mockFaultTypes[0],
    registeredBy: '1',
    registeredByUser: mockUsers[0],
    registeredAt: '2024-10-29T08:30:00',
    observations: 'El estudiante tuvo un altercado verbal con un compañero durante el recreo',
    reincidenceLevel: 3,
    hasEvidence: true,
    evidenceCount: 2,
    status: 'Activa',
  },
  {
    id: 'INC-2024-002',
    studentId: '2',
    student: mockStudents[1],
    faultTypeId: '3',
    faultType: mockFaultTypes[2],
    registeredBy: '1',
    registeredByUser: mockUsers[0],
    registeredAt: '2024-10-29T07:45:00',
    observations: 'Falta la camisa del uniforme',
    reincidenceLevel: 1,
    hasEvidence: false,
    evidenceCount: 0,
    status: 'Activa',
  },
  {
    id: 'INC-2024-003',
    studentId: '5',
    student: mockStudents[4],
    faultTypeId: '5',
    faultType: mockFaultTypes[4],
    registeredBy: '1',
    registeredByUser: mockUsers[0],
    registeredAt: '2024-10-28T07:55:00',
    observations: 'Llegó 15 minutos tarde sin justificación',
    reincidenceLevel: 2,
    hasEvidence: false,
    evidenceCount: 0,
    status: 'Activa',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIncidents: 247,
  incidentsToday: 12,
  incidentsThisWeek: 58,
  incidentsThisMonth: 187,
  studentsWithIncidents: 89,
  averageReincidenceLevel: 1.4,
  levelDistribution: {
    level0: 156,
    level1: 48,
    level2: 28,
    level3: 12,
    level4: 3,
  },
  topFaults: [
    { faultType: 'Llegada tarde', count: 45 },
    { faultType: 'Uniforme incompleto', count: 38 },
    { faultType: 'No presenta tarea', count: 32 },
    { faultType: 'Uso de lenguaje inapropiado', count: 18 },
    { faultType: 'Falta de respeto a compañeros', count: 12 },
  ],
  incidentsByGrade: [
    { grade: '1ro', count: 25 },
    { grade: '2do', count: 32 },
    { grade: '3ro', count: 41 },
    { grade: '4to', count: 38 },
    { grade: '5to', count: 52 },
    { grade: '6to', count: 59 },
  ],
};
